package com.ipn.mx.modelo.entidades;
// Generated 21/05/2018 03:23:42 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private String nombres;
     private String apellidos;
     private String rfc;
     private String calle;
     private String nexterior;
     private String ninterior;
     private String colonia;
     private String munDel;
     private String estado;
     private int cp;
     private String email;
     private Set<Factura> facturas = new HashSet<Factura>(0);

    public Cliente() {
    }

	
    public Cliente(String nombres, String apellidos, String calle, String nexterior, String colonia, String munDel, String estado, int cp, String email) {
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.calle = calle;
        this.nexterior = nexterior;
        this.colonia = colonia;
        this.munDel = munDel;
        this.estado = estado;
        this.cp = cp;
        this.email = email;
    }
    public Cliente(String nombres, String apellidos, String rfc, String calle, String nexterior, String ninterior, String colonia, String munDel, String estado, int cp, String email, Set<Factura> facturas) {
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.rfc = rfc;
       this.calle = calle;
       this.nexterior = nexterior;
       this.ninterior = ninterior;
       this.colonia = colonia;
       this.munDel = munDel;
       this.estado = estado;
       this.cp = cp;
       this.email = email;
       this.facturas = facturas;
    }
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNexterior() {
        return this.nexterior;
    }
    
    public void setNexterior(String nexterior) {
        this.nexterior = nexterior;
    }
    public String getNinterior() {
        return this.ninterior;
    }
    
    public void setNinterior(String ninterior) {
        this.ninterior = ninterior;
    }
    public String getColonia() {
        return this.colonia;
    }
    
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }
    public String getMunDel() {
        return this.munDel;
    }
    
    public void setMunDel(String munDel) {
        this.munDel = munDel;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Factura> getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set<Factura> facturas) {
        this.facturas = facturas;
    }




}


